# Generated by Django 4.2.1 on 2023-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0003_jugador_password_jugador_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jugador",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="jugador",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
