# Generated by Django 4.2.1 on 2023-08-08 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="token_code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("used", models.BooleanField(default=False)),
                ("date_used", models.DateTimeField(blank=True, null=True)),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("lock1", models.BooleanField(default=False)),
                ("lock2", models.BooleanField(default=False)),
                ("lock3", models.BooleanField(default=False)),
                ("lock4", models.BooleanField(default=False)),
                ("first_login", models.DateTimeField(blank=True, null=True)),
                ("winner", models.BooleanField(default=False)),
                ("winned_date", models.DateTimeField(blank=True, null=True)),
                (
                    "soulmate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="panel.account",
                    ),
                ),
            ],
        ),
    ]
