# Generated by Django 4.2.1 on 2023-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0002_rename_account_jugador"),
    ]

    operations = [
        migrations.AddField(
            model_name="jugador",
            name="password",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jugador",
            name="username",
            field=models.CharField(default=1535, max_length=100),
            preserve_default=False,
        ),
    ]
