# Generated by Django 4.2.1 on 2023-08-09 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("panel", "0004_alter_jugador_password_alter_jugador_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="token_code",
            new_name="Token",
        ),
    ]
